Lizeth
moneythink/decided pull request #2
Opened 2021-01-15 14:36 UTC by lvelascom

2021-01-18 13:44 UTC, lufte requested changes

2021-01-18 13:44 UTC, lufte commented on advisors/models.py
> +    code = models.CharField(max_length=140)
This model is the same as studentgroup. `archived`, `deleted` and `code` fields should be moved to the other model and this model should be removed.

2021-01-18 13:44 UTC, lufte commented on advisors/models.py
> +    students = models.ManyToManyField('students.Student')
Ideally we should always create the model for the many-to-many relation.  Check https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.ManyToManyField.through

2021-01-18 13:44 UTC, lufte commented on advisors/models.py
> +    title = models.CharField(max_length=10),
Add a ManyToMany field using AdvisorGroup as the `through` model.

2021-01-18 13:44 UTC, lufte commented on advisors/models.py
> +    advisors = models.ManyToManyField(Advisor)
Add the `through` attributes here too.

2021-01-18 13:44 UTC, lufte commented on advisors/models.py
> +    group = models.ForeignKey(Advisor, on_delete=models.CASCADE)
This foreign key is called group but points to Advisor.

2021-01-18 13:44 UTC, lufte commented on students/models.py
> +]
Follow the guidelines here (https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.Field.choices) for definig the choices of a field. Even better, we could use the new django constraints (https://docs.djangoproject.com/en/3.1/ref/models/constraints/#check) so this check is done at a RDBMS level.

2021-01-20 14:50 UTC, lufte approved these changes

2021-01-20 14:53 UTC, jjcp approved these changes

2021-01-20 15:00 UTC, merged